# Generated by Django 4.0.6 on 2022-07-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_folder_id_alter_folder_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_name',
            field=models.CharField(blank=True, default='Untitled', max_length=250),
        ),
    ]
